plugins:
  fixme:
    enabled: true
    config:
      strings:
      - # FIXME:
      - # TODO:

  markdownlint:
    enabled: true

  rubocop:
    enabled: true

  bundler-audit:
    enabled: true

engines:
  duplication:
    enabled: true
    config:
      languages:
        ruby:
          mass_threshold: 10
