version: "2"

plugins:
  fixme:
    enabled: true
    config:
      strings:
      - # FIXME:
      - # TODO:

  markdownlint:
    enabled: true

  rubocop:
    enabled: true
    channel: rubocop-0-67

  bundler-audit:
    enabled: true
