version: 2

plugins:
  brakeman:
    enabled: true

  bundler-audit:
    enabled: true

  csslint:
    enabled: true

  fixme:
    enabled: true
    config:
      strings:
      - # FIXME:
      - # TODO:

  duplication:
    enabled: true
    config:
      languages:
        - ruby

  markdownlint:
    enabled: true

  rubocop:
    enabled: false
