require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  Include:
    - Gemfile
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - db/schema.rb
    - tmp/**/*.rb
    - vendor/
    - lib/tasks/import/*.rake

#
# Linters
#

#
# Naming
#

#
# Metrics
#
Metrics/LineLength:
  Max: 150

Metrics/BlockLength:
  Exclude:
    - config/environments/*.rb
    - spec/**/*.rb

Metrics/MethodLength:
  Max: 15
  Exclude:
    - db/migrate/*.rb

# Metrics/ClassLength:
#   Enabled: false
#
# Metrics/ModuleLength:
#   Enabled: false

Metrics/AbcSize:
  Enabled: false

#
# Style
#
Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MixinUsage:
  Enabled: false

#
# Rails
#
Rails:
  Enabled: true

#
# RSpec
#
RSpec/DescribeClass:
  Exclude:
    - spec/features/*

RSpec/MultipleExpectations:
  Max: 20

RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

#
# Capybara
#
Capybara/FeatureMethods:
  Exclude:
    - spec/features/*
