require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  NewCops: enable
  Exclude:
    - bin/*
    - db/schema.rb
    - tmp/**/*
    - lib/tasks/import/*.rake
    - vendor/**/*

#
# Linters
#

#
# Naming
#

#
# Layout
#
Layout/LineLength:
  Max: 150

#
# Metrics
#
Metrics/BlockLength:
  Exclude:
    - config/routes.rb
    - config/environments/*.rb
    - lib/tasks/auto_annotate_models.rake
    - spec/**/*.rb

Metrics/MethodLength:
  Max: 15
  Exclude:
    - db/migrate/*.rb

Metrics/AbcSize:
  Enabled: false

#
# Style
#
Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/MixinUsage:
  Enabled: false

#
# Rails
#
Rails:
  Enabled: true

#
# RSpec
#
RSpec/DescribeClass:
  Exclude:
    - spec/features/*

RSpec/MultipleExpectations:
  Max: 30

RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  Max: 6

RSpec/MultipleMemoizedHelpers:
  Enabled: false

#
# Capybara
#
Capybara/FeatureMethods:
  Exclude:
    - spec/features/**/*
