require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  Exclude:
    - db/schema.rb
    - tmp/**/*
    - lib/tasks/import/*.rake

#
# Linters
#

#
# Naming
#

#
# Metrics
#
Metrics/LineLength:
  Max: 150

Metrics/BlockLength:
  Exclude:
    - config/routes.rb
    - config/environments/*.rb
    - lib/tasks/auto_annotate_models.rake
    - spec/**/*.rb

Metrics/MethodLength:
  Max: 15
  Exclude:
    - db/migrate/*.rb

# Metrics/ClassLength:
#   Enabled: false
#
# Metrics/ModuleLength:
#   Enabled: false

Metrics/AbcSize:
  Enabled: false

#
# Style
#
Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MixinUsage:
  Enabled: false

#
# Rails
#
Rails:
  Enabled: true

Rails/CreateTableWithTimestamps:
  Exclude:
    - db/migrate/20180317180735_install_audited.rb

#
# RSpec
#
RSpec/DescribeClass:
  Exclude:
    - spec/features/*

RSpec/MultipleExpectations:
  Max: 30

RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  Max: 6

#
# Capybara
#
Capybara/FeatureMethods:
  Exclude:
    - spec/features/**/*
