env:
  global:
    - CC_TEST_REPORTER_ID="e41b23cbcad58898c8f2d27aeb89b246db9a0b70345ae5472561c1c04cadd128"

dist: trusty
group: deprecated-2017Q4
sudo: required

language: ruby
rvm:
  - 2.3.4

cache:
  directories:
    - $HOME/.rvm
    - $HOME/bundle

bundler_args: --without production development --path $HOME/bundle

before_script:
  - sudo service mysql stop
  - docker-compose down
  - docker-compose up -d --build
  - sleep 20
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - docker-compose exec app cp .env.sample .env
  - docker-compose exec app rake db:drop db:create db:test:load
  - docker-compose exec app rspec
  - docker-compose exec app bundle exec brakeman -A -z
  - docker-compose exec app bundle exec bundle-audit update
  - docker-compose exec app bundle exec bundle-audit -v
  - docker-compose exec app bundle exec rubocop -c .rubocop.yml --force-exclusion

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - docker-compose down

services:
  - docker
