version: '3.7'

networks:
  development:

services:
  db:
    image: mariadb:10
    environment:
      MARIADB_USER: app
      MARIADB_PASSWORD: password
      MARIADB_DATABASE: app_development
      MARIADB_ROOT_PASSWORD: password
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
    ports:
      - 127.0.0.1:3306:3306
    networks:
      - development

  db_test:
    image: mariadb:10
    environment:
      MARIADB_USER: app
      MARIADB_PASSWORD: password
      MARIADB_DATABASE: app_test
      MARIADB_ROOT_PASSWORD: password
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
    ports:
      - 127.0.0.1:3307:3306
    networks:
      - development
