version: '3'

services:
  app:
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: example
    build: .
    command: ./docker-entrypoint.sh
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - default

  db:
    environment:
      MYSQL_ROOT_PASSWORD: example
    image: mariadb:10
    ports:
      - 3306:3306
    networks:
      - default

networks:
  default:
