FROM ruby:3.1.2-alpine
MAINTAINER Alexander Kadyrov <gruz0.mail@gmail.com>

RUN apk --update add --no-cache build-base tzdata mariadb-dev nodejs

# Create an user for running the application
RUN adduser -D user
USER user
WORKDIR /home/user
