name: Brakeman

on: [push]

jobs:
  brakeman:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true

    - name: Brakeman
      run: bundle exec brakeman -A -z
