name: RuboCop

on: [push]

jobs:
  rubocop:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: ['2.7', '2.5']

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: RuboCop
      run: bundle exec rubocop -DSE --force-exclusion -c .rubocop.yml
