name: RuboCop

on: [push]

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true

    - name: RuboCop
      run: bundle exec rubocop -DSE --force-exclusion -c .rubocop.yml
